triliovault-wlm-api_hosts:
  controller1:
    ip: <controller1_ip>
  controller2:
    ip: <controller2_ip>
  controller3:
    ip: <controller3_ip>

triliovault-wlm-workload_hosts:
  controller1:
    ip: <controller1_ip>
  controller2:
    ip: <controller2_ip>
  controller3:
    ip: <controller3_ip>

triliovault-wlm-cron_hosts:
  controller1:
    ip: <controller1_ip>
  controller2:
    ip: <controller2_ip>
  controller3:
    ip: <controller3_ip>

triliovault-wlm-scheduler_hosts:
  controller1:
    ip: <controller1_ip>
  controller2:
    ip: <controller2_ip>
  controller3:
    ip: <controller3_ip>