---
- name: Check triliovault containers
  become: true
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    environment: "{{ item.value.environment|default(omit) }}"
    pid_mode: "{{ item.value.pid_mode|default('') }}"
    ipc_mode: "{{ item.value.ipc_mode|default(omit) }}"
    privileged: "{{ item.value.privileged|default(False) }}"
    volumes: "{{ item.value.volumes|reject('equalto', '')|list }}"
    dimensions: "{{ item.value.dimensions }}"
    auth_username: "{{ triliovault_docker_username }}"
    auth_password: "{{ triliovault_docker_password }}"
    auth_registry: "{{ triliovault_docker_registry }}"    
  when:
    - inventory_hostname in groups[item.value.group]
    - inventory_hostname in groups[triliovault_wlm_api_group]
    - inventory_hostname in groups[triliovault_wlm_workloads_group]
    - inventory_hostname in groups[triliovault_wlm_scheduler_group]
    - inventory_hostname in groups[triliovault_wlm_cron_group]
    - item.value.enabled | bool
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart {{ item.key }} container"
