---

##Create_Cloud_Admin_Trust
- name: Verify cloudrc is present or not
  stat: path="/opt/triliovault-cloudrc"
  register: trilio_rc
  delegate_to: localhost

- name: Copy cloudrc triliovault-wlm-api container
  shell: docker cp /opt/triliovault-cloudrc triliovault_wlm_api:/opt/
  delegate_to: localhost
  when:
    - trilio_rc.stat.exists == true

- name: Create Cloud Admin Trust
  vars:
    triliovault_wlm_api: "{{ triliovault_services['triliovault-wlm-api'] }}"
  shell: |
    . /opt/triliovault-cloudrc && workloadmgr trust-create --is_cloud_trust True admin --insecure
  register: crt_cld_trust
  run_once: True
  delegate_to: "{{ groups[triliovault_wlm_api.group][0] }}"
  when: (result_wlm_api.rc == 0) and (result_wlm_workloads.rc == 0) and (result_wlm_scheduler.rc == 0) and (result_wlm_cron.rc == 0)

- name: Print Cloud admin trust output
  debug:
    msg: "{{ crt_cld_trust }}"
