---
- hosts: localhost
  become: true
  vars:
    - wlmcnf: "/etc/kolla/triliovault-wlm-api"
    - cloudrc: "/etc/kolla/triliovault-wlm-api/triliovault-cloudrc"
    - trust_cmd: "workloadmgr trust-create --is_cloud_trust True admin --insecure"

  tasks:
    - name: triliovault-cloud-admin-trust create container
      docker_container:
        name: "wlm_cloud_trust"
        image: "docker.io/trilio/centos-binary-trilio-wlm:5.0.SB-wallaby"
        command: " . {{ cloudrc }} && {{ trust_cmd }}"
        state: present
        volumes:
          - /etc/kolla/triliovault-wlm-api:/etc/triliovault-wlm:rw
          - /var/log/kolla/triliovault:/var/log/triliovault:rw
