---
- name: install packages on datamover api container | Install Tzdata package
  shell: "export DEBIAN_FRONTEND=noninteractive && apt install -y tzdata"

- name: Copy repo file
  template:
     src: triliovault.list
     dest: "{{ trilio_apt_repo_file_path }}"

- name: update cache
  command: apt-get update

- name: install packages on datamover api container | software-properties-common | python-dev | python-nova | curl
  apt:
    pkg:
      - software-properties-common
      - "{{ PYTHON_VERSION }}-dev"
      - "{{ PYTHON_VERSION }}-nova"
      - curl
    update_cache: yes
    state: latest

- name: Set Time Zone
  file:
    src: '/usr/share/zoneinfo/{{TIME_ZONE}}'
    dest: /etc/localtime
    owner: root
    group: root
    state: link
  ignore_errors: yes
  when: TIME_ZONE != ""
  notify:
    - update timezone

- name: create /tmp/datamover_url
  template:
     src: datamover_url
     dest: /tmp/datamover_url

- name: Install python3-dmapi pckg
  package:
    name: python3-dmapi
    state: latest
  when: PYTHON_VERSION=="python3"

- name: find out path of dmapi bianry
  shell: which dmapi-api
  register: dmapi_bin

- name: execute populate-conf binary
  shell: populate-conf
  register: populate_conf_ubuntu
  notify:
      - restart tvault-datamover-api

- name: ensure /tmp/datamover_url file is deleted
  file: path="/tmp/datamover_url" state=absent
