---

## DATABASE INFO
wlm_service_setup_host: "{{ openstack_service_setup_host | default('localhost') }}"
wlm_service_setup_host_python_interpreter: "{{ openstack_service_setup_host_python_interpreter | default((wlm_service_setup_host == 'localhost') | ternary(ansible_playbook_python, ansible_python['executable'])) }}"

wlm_galera_address: "{{ galera_address | default('127.0.0.1') }}"
wlm_galera_database: workloadmgr
wlm_galera_user: workloadmgr

wlm_galera_use_ssl: "{{ galera_use_ssl | default(False) }}"
wlm_galera_ssl_ca_cert: "{{ galera_ssl_ca_cert | default('/etc/ssl/certs/galera-ca.pem') }}"

wlm_galera_password: "{{ WLM_MYSQL_PASSWORD }}"
wlm_galera_port: 3306
wlm_service_role_name: "{{ cloud_admin_role | default('admin') }}"
wlm_bind_address: "{{ openstack_service_bind_address | default('0.0.0.0') }}"


## RPC
wlm_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group | default('rabbitmq_all') }}"
wlm_oslomsg_rpc_setup_host: "{{ (wlm_oslomsg_rpc_host_group in groups) | ternary(groups[wlm_oslomsg_rpc_host_group][0], 'localhost') }}"

wlm_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport | default('rabbit') }}"
wlm_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers | default('127.0.0.1') }}"

wlm_oslomsg_rpc_port: "{{ oslomsg_rpc_port | default('5672') }}"
wlm_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl | default(False) }}"

wlm_oslomsg_rpc_userid: workloadmgr
wlm_oslomsg_rpc_vhost: workloadmgr

wlm_oslomsg_rpc_ssl_version: "{{ oslomsg_rpc_ssl_version | default('TLSv1_2') }}"
wlm_oslomsg_rpc_ssl_ca_file: "{{ oslomsg_rpc_ssl_ca_file | default('') }}"

wlm_oslomsg_rpc_password: "{{RABBITMQ_PASSWORD}}"

## Notify
wlm_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group | default('rabbitmq_all') }}"
wlm_oslomsg_notify_setup_host: "{{ (wlm_oslomsg_notify_host_group in groups) | ternary(groups[wlm_oslomsg_notify_host_group][0], 'localhost') }}"

wlm_oslomsg_notify_transport: "{{ oslomsg_notify_transport | default('rabbit') }}"
wlm_oslomsg_notify_servers: "{{ oslomsg_notify_servers | default('127.0.0.1') }}"

wlm_oslomsg_notify_port: "{{ oslomsg_notify_port | default('5672') }}"
wlm_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl | default(False) }}"

wlm_oslomsg_notify_userid: "{{ wlm_oslomsg_rpc_userid }}"
wlm_oslomsg_notify_password: "{{ wlm_oslomsg_rpc_password }}"

wlm_oslomsg_notify_vhost: "{{ wlm_oslomsg_rpc_vhost }}"
wlm_oslomsg_notify_ssl_version: "{{ oslomsg_notify_ssl_version | default('TLSv1_2') }}"

wlm_oslomsg_notify_ssl_ca_file: "{{ oslomsg_notify_ssl_ca_file | default('') }}"

## (Qdrouterd) integration
## TODO(ansmith) Change structure when more backends will be supported
wlm_oslomsg_amqp1_enabled: "{{ wlm_oslomsg_rpc_transport == 'amqp' }}"


## Service Type and Data
wlm_service_region: "{{ service_region | default('RegionOne') }}"
wlm_service_name: workloadmgr

wlm_service_port: 8781
wlm_service_proto: http

wlm_service_publicuri_proto: "{{ openstack_service_publicuri_proto | default(wlm_service_proto) }}"
wlm_service_adminuri_proto: "{{ openstack_service_adminuri_proto | default(wlm_service_proto) }}"

wlm_service_internaluri_proto: "{{ openstack_service_internaluri_proto | default(wlm_service_proto) }}"
wlm_service_type: workloads

wlm_service_description: "Triliovault Workloadmgr API Service"
wlm_service_user_name: workloadmgr
wlm_service_project_name: "{{ triliovault_project_name | default('service')}}"

wlm_service_password: "{{ WLM_SERVICE_PASSWORD }}"
wlm_service_project_domain_id: "{{ wlm_project_domain_id | default('default')}}"
wlm_service_user_domain_id: "{{ triliovault_domain_id | default('default')}}"

wlm_service_publicuri: "{{ wlm_service_publicuri_proto }}://{{ external_lb_vip_address }}:{{ wlm_service_port }}"
wlm_service_publicurl: "{{ wlm_service_publicuri }}"

wlm_service_internaluri: "{{ wlm_service_internaluri_proto }}://{{ internal_lb_vip_address }}:{{ wlm_service_port }}"
wlm_service_internalurl: "{{ wlm_service_internaluri }}"

wlm_service_adminuri: "{{ wlm_service_adminuri_proto }}://{{ internal_lb_vip_address }}:{{ wlm_service_port }}"
wlm_service_adminurl: "{{ wlm_service_adminuri }}"

## Enable automatic parsing of X-Forwarded-Proto, etc. headers passed by the Load balancer.
wlm_proxy_headers_parsing: True


## Triliovault-wlm services
trilio_yum_repo_file_path: /etc/yum.repos.d/triliovault.repo
trilio_apt_repo_file_path: /etc/apt/sources.list.d/triliovault.list

## Default Triliovault username & Password
trilio_user_name: "triliovault"
trilio_user_password: "password"

## Triliovault configuration files
wlm_cfg: "/etc/triliovault-wlm/triliovault-wlm.conf"
wlm_api_paste: "/etc/triliovault-wlm/api-paste.ini"
triliovault_obj_sotre_cfg: "/etc/triliovault-object-store/triliovault-object-store.conf"
rootwrap_config: "/etc/triliovault-wlm/rootwrap.conf"
workloadmgr_rootwrap: "/usr/bin/workloadmgr-rootwrap"

glance_service_setup_host: "{{ openstack_service_setup_host | default('localhost') }}"
wlm_glance_api_servers: "{{ (glance_service_internalurl | default('http://localhost')) | urlsplit('scheme') ~ '://' ~ (glance_service_internalurl | default('http://localhost')) | urlsplit('netloc') }}"
glance_api_version: 2

trustee_role: "{{ trilio_trustee_role | default('creator') }}"
api_auth_port: 35357
osapi_workloads_listen_port: 8781

max_wait_upload: 10
workloads_workers: 4
client_retry_limit: 3

process_timeout: 300
misfire_grace_time: 600

wlm_log_dir: "/var/log/workloadmgr"
wlm_log_cfg: "/etc/triliovault-wlm/wlm_logging.conf"

## Keystone authentication middleware
wlm_keystone_auth_plugin: password
auth_type: password

auth_version: v3
keystone_auth_version: 3

## Required Directories
triliovault_mnt_dir: "/var/trilio/triliovault-mounts"
triliovault_obj_str: "/etc/triliovault-object-store/"

triliovault_log_dir: "/var/log/triliovault/"
triliovault_cfg_dir: "/etc/triliovault-wlm/"

triliovault_opt_dir: "/opt/triliovault-wlm/"
triliovault_virt_env: "/home/stack/wlm-venv"

signing_dir: "/var/cache/workloadmgr"
state_path: "/opt/stack/data/triliovault-wlm"

## api-paste.ini var
keystone_admin_port: 5000
