---
- name: Create triliovault log dir
  file:
    path: "{{ triliovault_log_dir }}"
    mode: '0755'
    recurse: yes
    owner: nova
    group: nova
    state: directory

- name: Create triliovault conf dir
  file:
    path: "{{ triliovault_cfg_dir }}"
    mode: '0755'
    recurse: yes
    owner: root
    group: nova
    state: directory

- name: Create triliovault mount dir
  file:
    path: "{{ triliovault_mnt_dir }}"
    state: directory
    mode: '0777'
