---
- name: Generate Rabbitmq Password
  set_fact: 
     RABBITMQ_PASSWORD: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
  run_once: true

- name: Generate wlmapi service Password
  set_fact: 
     WLMAPI_SERVICE_PASSWORD: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
  run_once: true

- name: Generate wlmapi mysql Password
  set_fact: 
     WLMAPI_MYSQL_PASSWORD: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
  run_once: true
