--- 

- name: Create Triliovault-cloudrc file    
  template:
    src: triliovault-cloudrc
    dest: /root/triliovault-cloudrc
    mode: '0777'
  delegate_to: localhost

- name: get neutron endpoint url
  shell: ". /root/triliovault-cloudrc && openstack endpoint list --insecure --service neutron --interface public -f value -c URL --os-cacert {{ os_ca_cert }}"
  register: neutron_endpoint
  delegate_to: localhost

- set_fact:
    neutron_endpoint_url: "{{ neutron_endpoint.stdout }}"

- name: get nova endpoint url
  shell: ". /root/triliovault-cloudrc && openstack endpoint list --insecure --service nova --interface public -f value -c URL --os-cacert {{ os_ca_cert }}"
  register: nova_endpoint
  delegate_to: localhost

- set_fact:
    nova_endpoint_url: "{{ nova_endpoint.stdout }}/%(project_id)s"

- name: get glance endpoint url
  shell: ". /root/triliovault-cloudrc && openstack endpoint list --insecure --service glance --interface public -f value -c URL --os-cacert {{ os_ca_cert }}"
  register: glance_endpoint
  delegate_to: localhost

- set_fact:
    glance_endpoint_url: "{{ glance_endpoint.stdout }}"
