---

- name: GET NOVA UID
  shell: /bin/bash -c "id -u {{ TVAULT_CONTEGO_EXT_USER }}"
  register: nova_uid

- set_fact:
    NOVA_UID: "{{ nova_uid.stdout }}"
    cacheable: yes

- name: GET NOVA GID
  shell: /bin/bash -c "id -g {{ TVAULT_CONTEGO_EXT_GROUP }}"
  register: nova_gid

- set_fact:
    NOVA_GID: "{{ nova_gid.stdout }}"
    cacheable: yes
