---
## Tasks Triliovault-wlm services

- name: Fetch nova and neutron public urls
  import_tasks: get_endpoint_list.yml
  tags:
    - triliovault-wlm
    - tvault-all-install

- name: Set workloadmgr database variables
  import_tasks: set_workloadmgr_db_vars.yml
  tags:
    - triliovault-wlm
    - tvault-all-install

- name: Get python details
  import_tasks: get_python.yml
  tags:
    - triliovault-wlm
    - triliovault-wlm-uninstall
    - tvault-all-install
    - tvault-all-uninstall

- import_tasks: uninstall_wlm_pckgs.yml
  tags:
    - triliovault-wlm-uninstall
    - tvault-all-uninstall

- import_tasks: delete_wlm_endpoints.yml
  tags:
    - triliovault-wlm-uninstall
    - tvault-all-uninstall

- name: Generate password
  import_tasks: generate_password.yml
  tags:
    - triliovault-wlm
    - tvault-all-install

- import_tasks: db_setup.yml
  when:
    - "wlm_db_setup_host"
  vars:
    _oslodb_setup_host: "{{ wlm_db_setup_host }}"
    _oslodb_ansible_python_interpreter: "{{ wlm_db_setup_python_interpreter }}"
    _oslodb_setup_endpoint: "{{ wlm_galera_address }}"
    _oslodb_setup_port: "{{ wlm_galera_port }}"
    _oslodb_databases:
      - name: "{{ wlm_galera_database }}"
        users:
          - username: "{{ wlm_galera_user }}"
            password: "{{ wlm_galera_password }}"
  tags:
    - triliovault-wlm
    - tvault-all-install

- import_tasks: mq_setup.yml
  when:
    - "wlm_oslomsg_rpc_setup_host"
  vars:
    _oslomsg_rpc_setup_host: "{{ wlm_oslomsg_rpc_setup_host }}"
    _oslomsg_rpc_userid: "{{ wlm_oslomsg_rpc_userid }}"
    _oslomsg_rpc_password: "{{ wlm_oslomsg_rpc_password }}"
    _oslomsg_rpc_vhost: "{{ wlm_oslomsg_rpc_vhost }}"
    _oslomsg_rpc_transport: "{{ wlm_oslomsg_rpc_transport }}"
    _oslomsg_notify_setup_host: "{{ wlm_oslomsg_notify_setup_host }}"
    _oslomsg_notify_userid: "{{ wlm_oslomsg_notify_userid }}"
    _oslomsg_notify_password: "{{ wlm_oslomsg_notify_password }}"
    _oslomsg_notify_vhost: "{{ wlm_oslomsg_notify_vhost }}"
    _oslomsg_notify_transport: "{{ wlm_oslomsg_notify_transport }}"
  tags:
    - triliovault-wlm
    - tvault-all-install

- name: Create Opensatck Endpoints
  import_tasks: create_endpoint.yml
  tags:
    - triliovault-wlm
    - tvault-all-install

- name: Install TRILIOVAULT WLM Services on CentOS/RHEL 
  import_tasks: install-centos.yml
  tags:
    - triliovault-wlm
    - tvault-all-install
  when: >
       (ansible_distribution_major_version>="8" and ansible_distribution=="CentOS") or
       (ansible_distribution_major_version>="8" and ansible_distribution=="RedHat")

- name: Install TRILIOVAULT WLM Services on Ubuntu/Debian
  import_tasks: install-ubuntu.yml
  tags:
    - triliovault-wlm
    - tvault-all-install
  when: >
        (ansible_distribution_major_version>"16.04" and ansible_distribution=="Ubuntu")

- import_tasks: create_cloud_admin_trust.yml
  tags:
    - create-trust
