---
## Tasks Triliovault-wlm services

- name: Fetch nova and neutron public urls
  import_tasks: get_endpoint_list.yml
  tags:
    - triliovault-wlm
    - triliovault-wlm-uninstall
    - tvault-all-install
    - tvault-all-uninstall

- name: Set workloadmgr database variables
  import_tasks: set_workloadmgr_db_vars.yml
  tags:
    - triliovault-wlm
    - triliovault-wlm-uninstall
    - tvault-all-install
    - tvault-all-uninstall

- name: Get python details
  import_tasks: get_python.yml
  tags:
    - triliovault-wlm
    - triliovault-wlm-uninstall
    - tvault-all-install
    - tvault-all-uninstall

- name: Generate password
  import_tasks: generate_password.yml
  tags:
    - triliovault-wlm
    - triliovault-wlm-uninstall
    - tvault-all-install
    - tvault-all-uninstall

- import_tasks: db_setup.yml
  when:
    - "wlmapi_db_setup_host"
  vars:
    _oslodb_setup_host: "{{ wlmapi_db_setup_host }}"
    _oslodb_ansible_python_interpreter: "{{ wlmapi_db_setup_python_interpreter }}"
    _oslodb_setup_endpoint: "{{ wlmapi_galera_address }}"
    _oslodb_setup_port: "{{ wlmapi_galera_port }}"
    _oslodb_databases:
      - name: "{{ wlmapi_galera_database }}"
        users:
          - username: "{{ wlmapi_galera_user }}"
            password: "{{ wlmapi_galera_password }}"
  tags:
    - triliovault-wlm
    - triliovault-wlm-uninstall
    - tvault-all-install
    - tvault-all-uninstall

- import_tasks: mq_setup.yml
  when:
    - "wlmapi_oslomsg_rpc_setup_host"
  vars:
    _oslomsg_rpc_setup_host: "{{ wlmapi_oslomsg_rpc_setup_host }}"
    _oslomsg_rpc_userid: "{{ wlmapi_oslomsg_rpc_userid }}"
    _oslomsg_rpc_password: "{{ wlmapi_oslomsg_rpc_password }}"
    _oslomsg_rpc_vhost: "{{ wlmapi_oslomsg_rpc_vhost }}"
    _oslomsg_rpc_transport: "{{ wlmapi_oslomsg_rpc_transport }}"
    _oslomsg_notify_setup_host: "{{ wlmapi_oslomsg_notify_setup_host }}"
    _oslomsg_notify_userid: "{{ wlmapi_oslomsg_notify_userid }}"
    _oslomsg_notify_password: "{{ wlmapi_oslomsg_notify_password }}"
    _oslomsg_notify_vhost: "{{ wlmapi_oslomsg_notify_vhost }}"
    _oslomsg_notify_transport: "{{ wlmapi_oslomsg_notify_transport }}"
  tags:
    - triliovault-wlm
    - triliovault-wlm-uninstall
    - tvault-all-install
    - tvault-all-uninstall

- name: Create Opensatck Endpoints
  import_tasks: create_endpoint.yml
  tags:
    - triliovault-wlm
    - triliovault-wlm-uninstall
    - tvault-all-install
    - tvault-all-uninstall

- name: Install WLM-API on CentOS/RHEL 
  import_tasks: install-centos.yml
  tags:
    - triliovault-wlm
    - triliovault-wlm-uninstall
    - tvault-all-install
    - tvault-all-uninstall
  when: >
       (ansible_distribution_major_version>="8" and ansible_distribution=="CentOS") or
       (ansible_distribution_major_version>="8" and ansible_distribution=="RedHat")

- name: Install WLM-API on Ubuntu/Debian
  import_tasks: install-ubuntu.yml
  tags:
    - triliovault-wlm
    - triliovault-wlm-uninstall
    - tvault-all-install
    - tvault-all-uninstall
  when: >
        (ansible_distribution_major_version>"16.04" and ansible_distribution=="Ubuntu")
