---

- name: Stop wlm-api service
  service:
    name: wlm-api
    state: stopped

- name: Stop wlm-workloads service
  service:
    name: wlm-workloads
    state: stopped

- name: Stop wlm-scheduler service
  service:
    name: wlm-scheduler
    state: stopped

- name: Stop wlm-cron service
  service:
    name: wlm-cron
    state: stopped

- name: Remove trilio yum repo
  file: path="{{trilio_yum_repo_file_path}}" state=absent
  when: >
    (ansible_distribution_major_version>="8" and ansible_distribution=="CentOS") or
    (ansible_distribution_major_version>="8" and ansible_distribution=="RedHat") or
    (ansible_distribution_major_version>="8" and ansible_distribution=="CentOS") or
    (ansible_distribution_major_version>="8" and ansible_distribution=="RedHat")

- name: Remove trilio apt repo
  file: path="{{trilio_apt_repo_file_path}}" state=absent
  when: >
    (ansible_distribution_major_version>="20.04" and ansible_distribution=="Ubuntu")

- name: Uninstall workloadmgr pckg
  package:
    name: workloadmgr
    state: absent

- name: Uninstall python-workloadmgrclient pckg
  package:
    name: python-workloadmgrclient
    state: absent
  when: ansible_distribution==ubuntu and PYTHON_VERSION=="python2"

- name: Uninstall python3-workloadmgrclient pckg
  package:
    name: python3-workloadmgrclient
    state: absent
  when: ansible_distribution==ubuntu and PYTHON_VERSION=="python3"

- name: Remove files from {{ triliovault_cfg_dir }}  dir
  file:
    path: "{{ triliovault_cfg_dir }}"
    state: absent

