---

- name: Stop wlm-api service
  service:
    name: wlm-api
    state: stopped
  ignore_errors: True

- name: Stop wlm-workloads service
  service:
    name: wlm-workloads
    state: stopped
  ignore_errors: True

- name: Stop wlm-scheduler service
  service:
    name: wlm-scheduler
    state: stopped
  ignore_errors: True

- name: Stop wlm-cron service
  service:
    name: wlm-cron
    state: stopped
  ignore_errors: True

- name: Remove trilio yum repo
  file: path="{{trilio_yum_repo_file_path}}" state=absent
  ignore_errors: True
  when: >
    (ansible_distribution_major_version>="8" and ansible_distribution=="CentOS") or
    (ansible_distribution_major_version>="8" and ansible_distribution=="RedHat") or
    (ansible_distribution_major_version>="8" and ansible_distribution=="CentOS") or
    (ansible_distribution_major_version>="8" and ansible_distribution=="RedHat")

- name: Remove trilio apt repo
  file: path="{{trilio_apt_repo_file_path}}" state=absent
  ignore_errors: True
  when: >
    (ansible_distribution_major_version>="20.04" and ansible_distribution=="Ubuntu")

- name: Uninstall workloadmgr packages
  package:
    name: 
      - workloadmgr
      - python3-workloadmgrclient
      - python3-contegoclient
    state: absent

- name: Uninstall python3-s3-fuse-plugin packages
  package:
    name: 
      - python3-s3-fuse-plugin
    state: absent
  when: NFS == False

- name: Uninstall python3-s3fuse-plugin packages
  package:
    name: 
      - python3-s3fuse-plugin
    state: absent
  when: NFS == True

- name: Remove files from {{ triliovault_cfg_dir }}  dir
  file:
    path: "{{ triliovault_cfg_dir }}"
    state: absent
  ignore_errors: True
