---

- name: Update the nova system user UID
  user:
    name: "{{ TVAULT_CONTEGO_EXT_USER }}"
    uid: "{{ NOVA_UID }}"
    group: " {{ TVAULT_CONTEGO_EXT_GROUP }} "
    system: "yes"

- name: Update the nova system group GID
  group:
    name: "{{ TVAULT_CONTEGO_EXT_GROUP }} "
    gid: "{{ NOVA_GID }}"
    non_unique: "yes"
    state: "present"
    system: "yes"


