---

- name: Setup trilio yum repo for queens
  template:
     src: triliovault.repo
     dest: "{{trilio_yum_repo_file_path}}"

- name: Install packages on horizon container | centos-release-openstack-{{OPENSTACK_DIST}}
  yum:
    update_cache: yes
    name:
      - "centos-release-openstack-{{OPENSTACK_DIST | lower}}"
    state: latest

- name: Install python3-tvault-horizon-plugin packages
  package:
    name:
      - python3-tvault-horizon-plugin-el8
      - python3-workloadmgrclient 
      - python3-contegoclient
    state: latest
  notify:
     - restart webserver
  when: PYTHON_VERSION=="python3" and ansible_distribution_major_version>="8"
