- name: ensure that {{TRILIOVAULT_MNT_DIR}} is present
  file: name="{{TRILIOVAULT_MNT_DIR}}" mode={{TRILIOVAULT_MNT_DIR_MODE}} owner={{TVAULT_CONTEGO_EXT_USER}} group={{TVAULT_CONTEGO_EXT_GROUP}} state=directory

- block:
  - name: TRILIOVAULT_MNT_DIR_OLD present or not
    stat: path="{{TRILIOVAULT_MNT_DIR_OLD}}"
    register: tvault_data_dir_old

  - name: Remove file from TRILIOVAULT_MNT_DIR_OLD
    shell: rm -rf {{TRILIOVAULT_MNT_DIR_OLD}}/*
    when: tvault_data_dir_old.stat.exists == True

  - name: Ensure TRILIOVAULT_MNT_DIR_OLD directory has permission
    file: name="{{TRILIOVAULT_MNT_DIR_OLD}}" owner={{TVAULT_CONTEGO_EXT_USER}} group={{TVAULT_CONTEGO_EXT_GROUP}}
    when: tvault_data_dir_old.stat.exists == True

  - name: ensure that {{TRILIOVAULT_MNT_DIR_OLD}} is present
    file: name="{{TRILIOVAULT_MNT_DIR_OLD}}" mode={{TRILIOVAULT_MNT_DIR_MODE}} owner={{TVAULT_CONTEGO_EXT_USER}} group={{TVAULT_CONTEGO_EXT_GROUP}} state=directory
  when: NFS != True

- name: create logrotate file for tvault-contego.log
  copy: src={{files_path}}/files/tvault-contego  dest=/etc/logrotate.d/tvault-contego
