---
- set_fact:
    nfsmount: "{{TVAULT_DATA_DIR}}"

- set_fact:
    triliovault_storage_nfs_export: "{{triliovault_nfs_map[inventory_hostname].split(',')}}"
  when: multi_ip_nfs_enabled == True

- set_fact:
    triliovault_storage_nfs_export: "{{NFS_SHARES}}"
  when: multi_ip_nfs_enabled == False

- name: Ensure {{nfsmount}} directory exists
  action: file path={{nfsmount}} state=directory

- set_fact:
      NFS_OPTIONS: "{{NFS_OPTS}}"
  when: NFS_OPTS != ""

- set_fact:
      NFS_OPTIONS: "nolock,soft,timeo=180,intr,lookupcache=none,nfsvers=3"
  when: NFS_OPTS == ""

- debug: msg="value of NFS_OPTIONS is:{{NFS_OPTIONS}}" verbosity={{ verbosity_level }}

- debug: msg="value of NFS_SHARES is:{{triliovault_storage_nfs_export}}" verbosity={{verbosity_level}}

- name: Ensure NFS common is installed when Ubuntu
  apt: name=nfs-common state=present update_cache=yes
  when: ansible_distribution=="Ubuntu"

- name: Ensure NFS Utils is installed when Centos/RedHat
  yum: name=nfs-utils state=present update_cache=yes
  when: >
    (ansible_distribution_major_version=="7" and ansible_distribution=="CentOS") or
    (ansible_distribution_major_version=="7" and ansible_distribution=="RedHat") or
    (ansible_distribution_major_version=="8" and ansible_distribution=="CentOS") or
    (ansible_distribution_major_version=="8" and ansible_distribution=="RedHat")

- block:
    - include_tasks: validate_nfs.yml
      vars:
        item1: "{{item}}"
      with_items: "{{triliovault_storage_nfs_export}}"
  when: NFS == True
