
- set_fact: 
    virtual_env_path: "/openstack/venvs/nova-{{ venv_tag }}"
  when: >
        ( nova_virtual_env is undefined )

- set_fact: 
    virtual_env_path: "{{ nova_virtual_env }}"
  when: > 
        ( nova_virtual_env is defined )

- name: Check stat virtual env path
  stat:
    path: "{{ virtual_env_path }}"
  register: chk_nova_pth

- name: Failed when nova virt env not found
  fail: 
    msg: "Anisble Failed Cause Path {{ virtual_env_path }} Not Found"
  when: > 
        ( chk_nova_pth.stat.exists == false )

- set_fact:
    virtual_env: ". {{virtual_env_path}}/bin/activate"

- set_fact: NOVA_COMPUTE_FILTERS_FILE={{virtual_env_path}}/etc/nova/rootwrap.d/compute.filters

- debug:
    msg: "NOVA_COMPUTE_FILTERS_FILE: {{NOVA_COMPUTE_FILTERS_FILE}}"
    verbosity: "{{ verbosity_level }}"
