- name: set external object store to tvault_contego_s3_ext if S3 is true
  set_fact:
       TVAULT_CONTEGO_EXT_OBJECT_STORE: "{{TVAULT_CONTEGO_EXT_S3}}"
  when: object_store == True and S3 == True

- debug: msg="external s3:{{TVAULT_CONTEGO_EXT_S3}}" verbosity={{verbosity_level}}

- name: Create {{VAULT_S3_SSL_CERT_DIR}} directory
  file: name="{{VAULT_S3_SSL_CERT_DIR}}"  state=directory
  when:
      - VAULT_S3_SSL_CERT != ""
      - S3|bool == True
      - s3_type == Other_S3_Compatible
  tags:
    - update_cfg

- name: check {{VAULT_S3_SSL_CERT}} is present or not
  stat: path="{{VAULT_S3_SSL_CERT}}"
  register: tvault_ssl_cert_output
  delegate_to: localhost
  when:
      - VAULT_S3_SSL_CERT != ""
      - S3|bool == True
      - s3_type == Other_S3_Compatible
  tags:
    - update_cfg

- name: Deploy user provided Tvault s3 {{VAULT_S3_SSL_CERT}}
  copy:
    src: "{{VAULT_S3_SSL_CERT}}"
    dest: "{{VAULT_S3_SSL_CERT_PATH}}"
    owner: nova
    group: nova
    mode: '640'
  when:
    - VAULT_S3_SSL_CERT != ""
    - S3|bool == True
    - s3_type == Other_S3_Compatible
    - tvault_ssl_cert_output.stat.exists == true
  tags:
    - update_cfg

- name: populate object store parameters in conf file
  template:
    src: tvault-object-store.conf.j2
    dest: "{{TVAULT_OBJECT_STORE_CONF}}"
    owner: root
    group: nova
    mode: '755'
  tags:
    - update_cfg

- name: systemd to reread configs
  systemd:
    daemon_reload: yes
  when:
    - S3|bool == True
  tags:
    - update_cfg

- name: Start triliovault-object-store service
  service:
    name: tvault-object-store
    state: started
  ignore_errors: yes
  when:
    - S3|bool == True
  tags:
    - update_cfg


