---
- import_tasks: get_venv.yml

- name: Remove tvault-contego-virtenv.tar.gz
  file: path=tvault-contego-virtenv.tar.gz state=absent

- name: change ownership of virtenv dir(/home/tvault)
  file: path={{TVAULT_CONTEGO_VIRTENV}} state=directory mode=765 owner="{{TVAULT_CONTEGO_EXT_USER}}" group="{{TVAULT_CONTEGO_EXT_GROUP}}"

- name: ensure that /var/log/tvault-contego file is present
  file: path="/var/log/tvault-contego" state=directory mode=750 owner="{{TVAULT_CONTEGO_EXT_USER}}" group="{{TVAULT_CONTEGO_EXT_GROUP}}"

- name: get tvault contego binary path
  shell: "{{virtual_env}} && which tvault-contego"
  register: tvault_contego_bin_path

- debug: msg="tvault_contego_bin_path={{tvault_contego_bin_path}}" verbosity="{{ verbosity_level }}"

- name: get privsep-helper binary path
  shell: "{{virtual_env}} && which privsep-helper"
  register: privsep_bin_path

- debug: msg="privsep_bin_path={{privsep_bin_path.stdout}}" verbosity="{{ verbosity_level }}"
