---
- name: ensure tvault-object-store service is stopped
  service: name=tvault-object-store  state=stopped enabled=no
  ignore_errors: yes

- name: stop datamover extension service
  service: name=tvault-contego state=stopped enabled=no
  ignore_errors: yes

- name: uninstall tvault-contego deb package when using python2
  apt:
     name:
        - s3-fuse-plugin
        - tvault-contego
     state: absent
     allow_unauthenticated: yes
     purge: yes
  when: PYTHON_VERSION=="python2"
  
- name: uninstall tvault-contego deb package when using python3
  apt:
     name:
       - python3-s3-fuse-plugin
       - python3-tvault-contego
     state: absent
     allow_unauthenticated: yes
     purge: yes
  when: PYTHON_VERSION=="python3"
