{{/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.configmap_etc }}
{{- $envAll := . }}

{{/* **********************************************************************
     set triliovault_datamover_api.conf conf parameters
     **********************************************************************
*/}}


{{- if empty .Values.conf.datamover_api.keystone_authtoken.www_authenticate_uri -}}
{{- $_ := tuple "identity" .Values.conf.triliovault.interface "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup" | set .Values.conf.datamover_api.keystone_authtoken "www_authenticate_uri" -}}
{{- end -}}

{{- if empty .Values.conf.datamover_api.keystone_authtoken.auth_url -}}
{{- $_ := tuple "identity" .Values.conf.triliovault.interface "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup" | set .Values.conf.datamover_api.keystone_authtoken "auth_url" -}}
{{- end -}}

{{- if empty .Values.conf.datamover_api.keystone_authtoken.region_name -}}
{{- $_ := set .Values.conf.datamover_api.keystone_authtoken "region_name" .Values.endpoints.identity.auth.triliovault_datamover.region_name -}}
{{- end -}}

{{- if empty .Values.conf.datamover_api.keystone_authtoken.project_name -}}
{{- $_ := set .Values.conf.datamover_api.keystone_authtoken "project_name" .Values.endpoints.identity.auth.triliovault_datamover.project_name -}}
{{- end -}}

{{- if empty .Values.conf.datamover_api.keystone_authtoken.project_domain_name -}}
{{- $_ := set .Values.conf.datamover_api.keystone_authtoken "project_domain_name" .Values.endpoints.identity.auth.triliovault_datamover.project_domain_name -}}
{{- end -}}

{{- if empty .Values.conf.datamover_api.keystone_authtoken.user_domain_name -}}
{{- $_ := set .Values.conf.datamover_api.keystone_authtoken "user_domain_name" .Values.endpoints.identity.auth.triliovault_datamover.user_domain_name -}}
{{- end -}}

{{- if empty .Values.conf.datamover_api.keystone_authtoken.username -}}
{{- $_ := set .Values.conf.datamover_api.keystone_authtoken "username" .Values.endpoints.identity.auth.triliovault_datamover.username -}}
{{- end -}}

{{- if empty .Values.conf.datamover_api.keystone_authtoken.password -}}
{{- $_ := set .Values.conf.datamover_api.keystone_authtoken "password" .Values.endpoints.identity.auth.triliovault_datamover.password -}}
{{- end -}}

{{- if empty .Values.conf.datamover_api.keystone_authtoken.memcached_servers -}}
{{- $_ := tuple "oslo_cache" "internal" "memcache" . | include "helm-toolkit.endpoints.host_and_port_endpoint_uri_lookup" | set .Values.conf.datamover_api.keystone_authtoken "memcached_servers" -}}
{{- end -}}


{{- if empty .Values.conf.datamover_api.keystone_authtoken.memcache_secret_key -}}
{{- $_ := set .Values.conf.datamover_api.keystone_authtoken "memcache_secret_key" ( default ( randAlphaNum 64 ) .Values.endpoints.oslo_cache.auth.memcache_secret_key ) -}}
{{- end -}}

{{- if .Values.manifests.secret_ca_bundle -}}
{{- $_ := set .Values.conf.datamover_api.keystone_authtoken "cafile" "/etc/ssl/certs/openstack-ca-bundle.pem" -}}
{{- else -}}
{{- $_ := set .Values.conf.datamover_api.keystone_authtoken "cafile" ""  -}}
{{- end -}}


{{- if empty .Values.conf.datamover_api.database.connection -}}
{{- $connection := tuple "oslo_db_triliovault_datamover" "internal" "triliovault_datamover" "mysql" . | include "helm-toolkit.endpoints.authenticated_endpoint_uri_lookup" -}}
{{- if .Values.manifests.certificates -}}
{{- $_ := (printf "%s?charset=utf8&ssl_ca=/etc/mysql/certs/ca.crt&ssl_key=/etc/mysql/certs/tls.key&ssl_cert=/etc/mysql/certs/tls.crt&ssl_verify_cert" $connection ) | set .Values.conf.datamover_api.database "connection" -}}
{{- else -}}
{{- $_ := set .Values.conf.datamover_api.database "connection" $connection -}}
{{- end -}}
{{- end -}}



{{- if empty .Values.conf.datamover_api.DEFAULT.dmapi_workers -}}
{{- $_ := set .Values.conf.datamover_api.DEFAULT "dmapi_workers" .Values.conf.triliovault.datamover_api_workers -}}
{{- end -}}

{{- if empty .Values.conf.datamover_api.DEFAULT.transport_url -}}
{{- $_ := tuple "oslo_messaging_nova" "internal" "nova" "amqp" . | include "helm-toolkit.endpoints.authenticated_transport_endpoint_uri_lookup" | set .Values.conf.datamover_api.DEFAULT "transport_url" -}}
{{- end -}}


{{/* **********************************************************************
     set logging.conf conf parameters
     **********************************************************************
*/}}


{{- if and (empty .Values.conf.logging.handler_fluent) (has "fluent" .Values.conf.logging.handlers.keys) -}}
{{- $fluentd_host := tuple "fluentd" "internal" $envAll | include "helm-toolkit.endpoints.hostname_namespaced_endpoint_lookup" }}
{{- $fluentd_port := tuple "fluentd" "internal" "service" $envAll | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
{{- $fluent_args := printf "('%s.%s', '%s', %s)" .Release.Namespace .Release.Name $fluentd_host $fluentd_port }}
{{- $handler_fluent := dict "class" "fluent.handler.FluentHandler" "formatter" "fluent" "args" $fluent_args -}}
{{- $_ := set .Values.conf.logging "handler_fluent" $handler_fluent -}}
{{- end -}}

{{- if and (empty .Values.conf.logging.formatter_fluent) (has "fluent" .Values.conf.logging.formatters.keys) -}}
{{- $formatter_fluent := dict "class" "oslo_log.formatters.FluentFormatter" -}}
{{- $_ := set .Values.conf.logging "formatter_fluent" $formatter_fluent -}}
{{- end -}}





{{/* **********************************************************************
     DONE
     **********************************************************************
*/}}
---
apiVersion: v1
kind: Secret
metadata:
  name: triliovault-etc-datamover-api
type: Opaque
data:
  triliovault-datamover-api.conf: {{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.datamover_api | b64enc }}
  logging.conf: {{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.logging | b64enc }}
  datamover_api_logging.conf: {{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.datamover_api_logging | b64enc }}
  object_store_logging.conf: {{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.object_store_logging | b64enc }}
  policy.yaml: {{ toYaml .Values.conf.policy | b64enc }}
  fuse.conf: {{ .Values.conf.fuse | b64enc }}
  s3-cert.pem: {{ .Files.Get "files/s3-cert.pem" | default "" | b64enc }}
  api-paste.ini: {{ tuple "bin/_api-paste.ini.tpl" . | include "helm-toolkit.utils.template" | b64enc }}
  nova-compute.conf: {{ tuple "bin/_triliovault-nova-compute.conf.tpl" . | include "helm-toolkit.utils.template" | b64enc }}
  {{- if .Values.ceph.enabled }}
  ceph.conf: {{ tuple "bin/_triliovault-ceph.conf.tpl" . | include "helm-toolkit.utils.template" | b64enc }}
  {{ end }}
{{- end }}
