##common editable parameters required for installing 
## Triliovault-workloamdgr, Triliovault-horizon-plugin, Triliovault-contego and Triliovault-datamover-api services

##Time Zone
TIME_ZONE: "Etc/UTC"

#Update TVAULT package version here, we will install mentioned version plugins for Example# TVAULT_PACKAGE_VERSION: 3.3.36
TVAULT_PACKAGE_VERSION: 4.2.64

# Update Openstack dist code name like ussuri etc.
OPENSTACK_DIST: wallaby

#Need to add the following statement in nova sudoers file
#nova ALL = (root) NOPASSWD: /home/tvault/.virtenv/bin/privsep-helper *
#These changes require for Datamover, Otherwise Datamover will not work
#Are you sure? Please set variable to 
#  UPDATE_NOVA_SUDOERS_FILE: proceed
#other wise ansible tvault-contego installation will exit
UPDATE_NOVA_SUDOERS_FILE: proceed

##### Select snapshot storage type #####
#Details for NFS as snapshot storage , NFS_SHARES should begin with "-".
##True/False
NFS: False
NFS_SHARES: 
          - sample_nfs_server_ip1:sample_share_path
          - sample_nfs_server_ip2:sample_share_path

## If NFS_OPTS is empty then default value will be "nolock,soft,timeo=180,intr,lookupcache=none,nfsvers=3"
NFS_OPTS: ""

## Valid for 'nfs' backup target only.
## If backup target NFS share supports multiple endpoints/ips but in backend it's a single share then
## set 'multi_ip_nfs_enabled' parameter to 'True'. Otherwise it's value should be 'False'
multi_ip_nfs_enabled: False

#### Details for S3 as snapshot storage
##True/False
S3: False
VAULT_S3_ACCESS_KEY: sample_s3_access_key
VAULT_S3_SECRET_ACCESS_KEY: sample_s3_secret_access_key
VAULT_S3_REGION_NAME: sample_s3_region_name
VAULT_S3_BUCKET: sample_s3_bucket
VAULT_S3_SIGNATURE_VERSION: default
#### S3 Specific Backend Configurations
#### Provide one of follwoing two values in s3_type variable, string's case should be match
#Amazon/Other_S3_Compatible
s3_type: sample_s3_type
#### Required field(s) for all S3 backends except Amazon
VAULT_S3_ENDPOINT_URL: ""
#True/False
VAULT_S3_SECURE: True
VAULT_S3_SSL_CERT: ""

###details of datamover API
##If SSL is enabled "DMAPI_ENABLED_SSL_APIS" value should be dmapi.
#DMAPI_ENABLED_SSL_APIS: dmapi
##If SSL is disabled "DMAPI_ENABLED_SSL_APIS" value should be empty.
DMAPI_ENABLED_SSL_APIS: ""
DMAPI_SSL_CERT: ""
DMAPI_SSL_KEY: ""

## Triliovault dmapi_workers count
## Default value of dmapi_workers is 16
dmapi_workers: 16

#### Any service is using Ceph Backend then set ceph_backend_enabled value to True
#True/False
ceph_backend_enabled: False

## Provide Horizon Virtual Env path from Horizon_container
## e.g. '/openstack/venvs/horizon-23.1.0'
horizon_virtual_env: '/openstack/venvs/horizon*'

#Set verbosity level and run playbooks with -vvv option to display custom debug messages
verbosity_level: 3

#******************************************************************************************************************************************************************
###static fields for tvault contego extension ,Please Do not Edit Below Variables
#******************************************************************************************************************************************************************
#SSL path
DMAPI_SSL_CERT_DIR: /opt/config-certs/dmapi
VAULT_S3_SSL_CERT_DIR: /opt/config-certs/s3
RABBITMQ_SSL_DIR: /opt/config-certs/rabbitmq
DMAPI_SSL_CERT_PATH: /opt/config-certs/dmapi/dmapi-ca.pem
DMAPI_SSL_KEY_PATH: /opt/config-certs/dmapi/dmapi.key
VAULT_S3_SSL_CERT_PATH: /opt/config-certs/s3/ca_cert.pem
RABBITMQ_SSL_CERT_PATH: /opt/config-certs/rabbitmq/rabbitmq.pem
RABBITMQ_SSL_KEY_PATH: /opt/config-certs/rabbitmq/rabbitmq.key
RABBITMQ_SSL_CA_CERT_PATH: /opt/config-certs/rabbitmq/rabbitmq-ca.pem

PORT_NO: 8085
PYPI_PORT: 8081
DMAPI_USR: dmapi
DMAPI_GRP: dmapi

## tvault contego file path
TVAULT_CONTEGO_CONF: /etc/triliovault-datamover/triliovault-datamover.conf
#TVAULT_CONTEGO_CONF: /etc/triliovault-datamover/tvault-contego.conf
TVAULT_OBJECT_STORE_CONF: /etc/triliovault-object-store/triliovault-object-store.conf
NOVA_CONF_FILE: /etc/nova/nova.conf

## Nova distribution specific configuration file path
NOVA_DIST_CONF_FILE: /usr/share/nova/nova-dist.conf
TVAULT_CONTEGO_EXT_USER: nova
TVAULT_CONTEGO_EXT_GROUP: nova
#TVAULT_DATA_DIR_MODE: 0775
#TVAULT_DATA_DIR_OLD: /var/triliovault
#TVAULT_DATA_DIR: /var/trilio/triliovault-mounts
TVAULT_CONTEGO_VIRTENV: /home/tvault
TVAULT_CONTEGO_VIRTENV_PATH: "{{TVAULT_CONTEGO_VIRTENV}}/.virtenv"
TVAULT_CONTEGO_EXT_BIN: "{{TVAULT_CONTEGO_VIRTENV_PATH}}/bin/tvault-contego"
TVAULT_CONTEGO_EXT_PYTHON: "{{TVAULT_CONTEGO_VIRTENV_PATH}}/bin/python"
TVAULT_CONTEGO_EXT_OBJECT_STORE: ""
TVAULT_CONTEGO_EXT_BACKEND_TYPE: ""

TVAULT_CONTEGO_EXT_S3: "{{TVAULT_CONTEGO_VIRTENV_PATH}}/lib/python2.7/site-packages/contego/nova/extension/driver/s3vaultfuse.py"
privsep_helper_file: /home/tvault/.virtenv/bin/privsep-helper
pip_version: 7.1.2
virsh_version: "1.2.8"
contego_service_file_path: /etc/systemd/system/tvault-contego.service
contego_service_ulimits_count: 65536
contego_service_debian_path: /etc/init/tvault-contego.conf

objstore_service_file_path:  /etc/systemd/system/tvault-object-store.service
objstore_service_debian_path: /etc/init/tvault-object-store.conf

ubuntu: "Ubuntu"
centos: "CentOS"
redhat: "RedHat"
Amazon: "Amazon"
Other_S3_Compatible: "Other_S3_Compatible"
tvault_datamover_api: tvault-datamover-api

datamover_service_file_path: /etc/systemd/system/tvault-datamover-api.service
datamover_service_debian_path: /etc/init/tvault-datamover.conf

datamover_log_dir: /var/log/triliovault
trilio_yum_repo_file_path: /etc/yum.repos.d/trilio.repo

## Triliovault pckg version
triliovault_version: ""

## Cloud Details
cloud_admin_project_name: ""
cloud_admin_project_id: ""

cloud_admin_domain_name: ""
cloud_admin_domain_id: ""

cloud_admin_username: ""
cloud_admin_password: ""

OS_ENDPOINT_TYPE: ""

OS_REGION: ""
OS_AUTH_URL: ""

os_ca_cert: "/etc/openstack_deploy/ssl/ca.crt"

## Specify installation is done trhough python pip packages e.g. if venv is /home/stack/venv, then
## venv_path: "/home/stack/venv"
venv_path: ""

## Uncomment 'cloud_admin_role' if user wants to set any other role than 'admin'
## Specify the role

cloud_admin_role: "admin"

## Uncomment the varibale wlm_service_project_name only if
## user wants to deploy triliovault-wlm in different projcet
## the default value of wlm_service_project_name 'service'

wlm_service_project_name: "service"

## Uncomment the variable wlm_user_domain_name namewhen
## user wants to deploy triliovualt-wlm components in different domain
## default value of wlm_user_domain_name is 'Default'

wlm_user_domain_name: "Default"

## Uncomment the variable wlm_user_domain_id when
## user wants to deploy triliovualt-wlm components in different domain
## default value of wlm_user_domain_id is 'default'

wlm_user_domain_id: "default"

## Uncomment 'wlm_project_domain_name' and set any value 
## Default value is other than 'Default'

wlm_project_domain_name : "Default"

## Uncomment 'wlm_project_domain_id' and set any value 
## Default value is other than 'default'

wlm_project_domain_id : "default"

## Triliovault trustee role default value is 'creator'
## If need to assign trustee_role other than default value
## Uncomment 'wlm_trustee_role' and assign the value

wlm_trustee_role: "creator"

